### ISSUE TITLE
Deleted pages are not removed from Azure when uploading new version

### ISSUE THREAD

**Issue by dud3** [SiliconStudio/xenko-docs#14]
Hi Guys the left menu on docs site, seem be looking a little bit strange, like it has an `iframe` on it:
![xenko-docs-001](https://cloud.githubusercontent.com/assets/5823644/14802770/cbd660e8-0b53-11e6-8283-d940bc8e631c.png)
![xenko-docs-002](https://cloud.githubusercontent.com/assets/5823644/14802771/cbd69608-0b53-11e6-9ce9-79e3abd4bcba.png)
![xenko-docs-003](https://cloud.githubusercontent.com/assets/5823644/14802772/cbd75840-0b53-11e6-97c2-27754161ff9a.png)

**Comment by Kryptos-FR** [comment]
Couldn't reproduce. What are the steps to achieve the same behavior?

**Comment by dud3** [comment]
Googling I ended up on this link: http://doc.xenko.com/1.6/manual/graphics/graphics-reference/graphics-device-reference/index.html

![xenko-docs-004](https://cloud.githubusercontent.com/assets/5823644/14829480/eab4b652-0beb-11e6-9566-e6f2a67688a9.png)

**Comment by xen2** [comment]
This page was removed from 1.6 doc at some point, and the html files are still uploaded.
It is not accessible from the TOC but still leftover in both Google and Azure.

I will check if we can have an option to delete files that don't exist anymore when updating doc to a new version.

**Comment by xen2** [comment]
Should be good from now on, files that don't exist anymore will be deleted on the remote server too when doing Azure upload/synchronization.
(for reference I had to add `/d` to https://github.com/davidebbo/WAWSDeploy parameters)

**Comment by xen2** [comment]
Thanks again for the report!
