### ISSUE TITLE
Manual - Low-level API - SpriteBatch etc. should cover the required setup of compostion renderer

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko-docs#32]
Hi,

Saw this [question](https://forums.xenko.com/t/rendering-text-via-spritebatch/858) on forums. I checked the manual and it doesn't really explain this at all.  Maybe just mention what's required and link to custom-scene-renderer.md??

Cheers,
dfkeenan

**Comment by jamesduffytokyo** [comment]
Done, added note and link to this and the SpriteFont page
