### ISSUE TITLE
I don't think the new article "Distribute a game" is applicable to all platforms. 

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko-docs#36]
Hi,

I think the new article "[Distribute a game](https://github.com/SiliconStudio/xenko-docs/blob/master-1.10/manual/files-and-folders/distribute-a-game.md)" is only really applicable to Windows and possibly Linux/Mac. For other platforms (UWP,Android, iOS) shouldn't you use the built in packaging provided by Visual Studio/Xamarian/XCode?

Cheers,
dfkeenan

**Comment by jamesduffytokyo** [comment]
@dfkeenan That's the old version of the doc - is the problem still present on the 2.0 version? http://doc.xenko.com/latest/manual/files-and-folders/distribute-a-game.html

**Comment by jamesduffytokyo** [comment]
@dfkeenan added another step (step 5) - does it cover it? http://doc.xenko.com/latest/manual/files-and-folders/distribute-a-game.html

**Comment by dfkeenan** [comment]
The new section is an improvement.  Just maybe double check the "Delete unnecessary files" section. I'm just not sure if UWP, Xamarian platforms put packages in places other than the "x64, x86, and Data" folders.    Though most people would probably just use the built in packaging/deployment stuff directly in Visual Studio and never go to the bin folders. Not sure about iOS though.

**Comment by jamesduffytokyo** [comment]
Have rewritten the section. According to @virgilebello , "those platforms automatically build packages.
so nothing you can delete anyway."
