### ISSUE TITLE
Link to Xenko logo regulations PDF broken.

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko-docs#39]
Hi,

Looking at the splash screen doco. The link to the "Xenko logo regulations PDF" does not work.

Might be a xenko.com problem rather than documentation.

Cheers,
dfkeenan

**Comment by Kryptos-FR** [comment]
Thanks for the report.

Looks like the link in the documentation is incorrect. The correct URL is: https://xenko.com/legal/xenko-logo-regulations.pdf
