### ISSUE TITLE
Code sample in "Write your own script or modify an existing one" of "animation-scripts.md" is not valid C#

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko-docs#44]
Hi,

Something seems to have gone wrong with this example.

```C#
public class AnimationClipExample : SyncScript
{
    // Public animation clips
    public AnimationClip idleClip;
    public AnimationClip walkClip;
    public AnimationClip runClip;

    //public variable to determine if model is running or walking
using SiliconStudio.Xenko.Engine;

namespace AdditiveAnimation
{
    public class AnimationClipExample : SyncScript
    {
```
The  first class declaration should be deleted and I think everything else above the `using` statement should be moved to the top of the following class declaration. Though those public `AnimationClip` fields might not be needed at all either. Not sure about API usage but they are not referenced in the subsequent code.

Cheers,
dfkeenan

**Comment by jamesduffytokyo** [comment]
Fixed, hopefully
