### ISSUE TITLE
Shader language syntax documentation out of date.

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko-docs#45]
It seems sometime between version 1.6 and 1.7 (just looking in branches) the `class` keyword was changed to `shader` but the documentation is still talking about classes.  There might be other things that have changed but that one is obvious.

**Comment by dfkeenan** [comment]
Looks like you have updated the example code but classes are talked about in quite a few spots through out the documents.

**Comment by jamesduffytokyo** [comment]
Can you give some examples of where?

**Comment by dfkeenan** [comment]
Well the file /manual/graphics/effects-and-shaders/shading-language/classes-mixins-and-inheritance.md talks about "classes".

/manual/graphics/effects-and-shaders/shading-language/composition.md  Mentions "classes" a couple of times. At least 2 times in opening paragraphs.

/manual/graphics/effects-and-shaders/shading-language/automatic-shader-stage-input-output.md

Might be easier to do a search?? https://github.com/SiliconStudio/xenko-docs/search?utf8=%E2%9C%93&q=class+path%3A%2Fmanual%2Fgraphics%2Feffects-and-shaders%2F&type=

That picks up a few extras that shouldn't be changed.

**Comment by jamesduffytokyo** [comment]
OK, thanks for that. I'm not a coder so I wasn't able to tell which mentions of class were appropriate and which weren't. Hopefully all up to date now...
