### ISSUE TITLE
Mention that scene hierarchy visible in editor is editor-only

### ISSUE THREAD

**Issue by jason-wilmans** [SiliconStudio/xenko-docs#46]
We read all docs regarding the scene hierarchy and still wasted 2-3 hours just setting up a basic one-root-one-child-scenario.

This little remark in the doc would have helped greatly:

"Note that the hierarchy displayed in the editor applies **only** in the editor. Whether or not child scenes are displayed in the editor, this relation does not apply at runtime. At runtime, child scenes always need to be loaded by code."

**Comment by xenux** [comment]
Thank you very much for the feedback we will improve this!

**Comment by jamesduffytokyo** [comment]
Thanks very much for this, and apologies for the trouble!

We've added your suggestion to the page: 
http://doc.xenko.com/latest/manual/game-studio/manage-scenes.html

**Comment by jason-wilmans** [comment]
Cool! :)
