### ISSUE TITLE
Create a model from code - incorrect example

### ISSUE THREAD

**Issue by Chaosus** [SiliconStudio/xenko-docs#48]
Hi xenko team. http://doc.xenko.com/latest/en/manual/scripts/create-a-model-from-code.html have incorrect example 
```
// Add one or more meshes using geometric primitives (eg spheres or cubes).
 var meshDraw = GeometricPrimitive.Sphere.New(GraphicsDevice).ToMeshDraw();

 var mesh = new Mesh { Draw = meshDraw }; 
 model.Meshes.Add(mesh);
```
There is no ToMeshDraw method anymore, and I did not found how to set geometric primitive from code anywhere... Please fix !

**Comment by Kryptos-FR** [comment]
`ToMeshDraw()` is an extension method. To use it you need to import the correct namespace:

```
using SiliconStudio.Xenko.Extensions;
```

**Comment by Chaosus** [comment]
Ah, thanks for answering.. I thinked that it has been removed in some version..
